### ISSUE TITLE
Question/Query are endpoints and refresh intervals supported?

### ISSUE THREAD

**Issue by psDevUK** [ironmansoftware/ud-forge#11]
Ok so I built my single page UD app a few times now but each time it errors:-
![Capture](https://user-images.githubusercontent.com/44211223/65698010-c4418580-e073-11e9-919e-adaa9be46b5d.PNG)
![Capture 2PNG](https://user-images.githubusercontent.com/44211223/65698100-eaffbc00-e073-11e9-9343-5d4c281a0fe1.PNG)
 I mean it's highly likely this is me being a dinlow but I'm using an SQL module im importing endpoints and refresh intervals and calling the dashboard like:-
 Start-UDDashboard -Port 10008 -Dashboard ($dash ) -Endpoint $Endpoint
Is there something I am missing or just being plain stupid?

**Comment by adamdriscoll** [comment]
@psDevUK I just found a bug in the JS code. Gonna release a new version right now. 

Can you also make sure to set the port to 8001 and use the -Wait parameter for Start-UDDashboard?

**Comment by psDevUK** [comment]
ok man I am still trying...and failing...but I know this must work as you posted it working...so I decided to now build your test dashboard the one you did....so about the New-BurntToastNotification did you have that moduled imported at the time of building to get that into the .exe or is there a special trick?

**Comment by psDevUK** [comment]
Hmmm so I found your demo page and literally just changed it to New-UdInputAction -Toast $Message instead of new-burntToastNotification and I still get this error when trying to launch the .exe 
![Capture](https://user-images.githubusercontent.com/44211223/65705238-f48f2100-e07f-11e9-90ad-571b1ff31b1f.PNG)
 But builds without errors.

**Comment by adamdriscoll** [comment]
You have powershell 6 or 7 installed?

**Comment by psDevUK** [comment]
running windows 10 x64 powershell 5

**Comment by adamdriscoll** [comment]
Try setting the -PowerShellHost parameter to powershell.

**Comment by psDevUK** [comment]
Yes you are the man @adamdriscoll please put that in the readme for all others using VS Code..You the man!
