### ISSUE TITLE
Error - npx : - Initializing Project Directory

### ISSUE THREAD

**Issue by HansenRene** [ironmansoftware/ud-forge#17]
I'm not having the best of luck building my first app.

Both Prerequisites is installed.

![image](https://user-images.githubusercontent.com/20628942/66118544-edfc2e80-e5d6-11e9-86f9-7c7877424c33.png)

**Comment by HansenRene** [comment]
Looks like its looking for Git?

![image](https://user-images.githubusercontent.com/20628942/66295682-30ca4900-e8ec-11e9-8a36-fb2abe612391.png)

(I'm one of those pesky Github Desktop users, so Git does not exist in my path).

**Comment by HansenRene** [comment]
~~Installing Git resolved the actual issue - I'm leaving this issue open as the addition of git as a prerequisite needs to be mentioned somewhere.~~

**Comment by HansenRene** [comment]
Well, Git solved the Git part of the issue.

Still getting this on 2 different machines, does not look healthy

![image](https://user-images.githubusercontent.com/20628942/66308768-25851680-e908-11e9-9f07-c423038dabe0.png)

**Comment by adamdriscoll** [comment]
Are those actually errors or is npm just using the error stream to write output? That's very strange because I don't see that in Windows PowerShell or PWSH. What version of PS\Windows are you running here? I didn't realize this thing needed git. I will add that to the pre-reqs.

**Comment by HansenRene** [comment]
W10 1903, latest version of powershell.

________________________________

**Comment by HansenRene** [comment]
It does indeed not look like actual errors no. I'm able to run the dashboard, and find the installer.

![image](https://user-images.githubusercontent.com/20628942/66389967-e61efe80-e9c9-11e9-8a80-dc872f05714b.png)
